language: python
dist: xenial
python:
  - 3.6
  - 3.7
git:
  depth: 3
addons:
  apt:
    packages:
      - openjdk-8-jre
install:
  - pip3 install -r requirements.txt
  - pyppeteer-install
script:
  - ./build -o test.html
  - ./run-tests -i test.html
  - html5validator --ignore="Property \"behavior\" doesn't exist." test.html
notifications:
  email:
    recipients:
      - diego@assencio.com
    on_success: change
on_failure: always
